#Special configuration file to run tests on Travis-CI via GitHub notifications
#See http://travis-ci.org/ for details
#
#Simplest way to get R installed for rpy2?
language: r
sudo: required

before_install:
  - "sudo apt-get install ncbi-blast"
  - "sudo apt-get install ncbi-blast+"
  - "sudo apt-get install mummer"
  - "sudo apt-get install python-numpy"
  - "sudo apt-get install python-scipy"
  - "sudo apt-get install python-pandas"
  - "sudo apt-get install python-matplotlib"
  - "sudo pip install -r requirements.txt"

install:
  - "sudo python setup.py install"

script:
  - make test

notifications:
  email: false
