#Special configuration file to run tests on Travis-CI via GitHub notifications
#See http://travis-ci.org/ for details
#
#Note when testing Python 3, the 'python' command will invoke Python 3
#and similarly for 'pip' too.

sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - "sudo apt-get install r-base"
  - "pip install -r requirements.txt"

install:
  - "python setup.py install"

script:
  - make test

notifications:
  email: false
